name: Check-in
on:
  # schedule every weekdays at 08:00 (UTC+7) / 03:00 (UTC)
  # in the past, "0 3 * * 1-5" runs at around 10:00 (UTC+7), so I changed it to "0 1 * * 1-5" to run at 08:00 (UTC+7)
  # already changed, but still late check-in at around (09:22 UTC+7)

  # Still late check-in https://github.com/helmisatria/talenta-attendance-automation/issues/5,
  # Need to change the cron to "0 0 * * 1-5" to run at around 08:00 (UTC+7)

  # changed to "20 0 * * 1-5" from "0 0 * * 1-5" expecting will run at around 08:20 (previously around 08:00)

  # -- 3 Feb 2023
  # changed to "10 0 * * 1-5" from "20 0 * * 1-5" expecting will run at around 08:30 (previously around 08:56)
  
  # -- 27 Feb 2023
  # changed to  "0 23 * * 0-4" expecting will run at around 08:50ish (previously around 09:56)
    
  # -- 28 Feb 2023
  # changed to  "0 1 * * 1-5" expecting will run at around 08:50ish (previously around 06:30 ish)
    # -- 3 March 2023
  # changed to  "30 23 * * 0-4" expecting will run at around 08:50ish (previously around 10:15 ish UTC+7)
      # -- 6 March 2023
  # changed to  "59 23 * * 0-4" expecting will run at around 07:00ish (previously around 06:38 ish UTC+7)
  
  # changed to  "25 01 * * 1-5" expecting will run at around 08:30ish (previously around 07:00 ish UTC+7)
      # -- 20 March 2023
      
  # changed to  "00 00 * * 1-5" expecting will run at around 08:30ish (previously around 09:00 ish UTC+7)
      # -- 21 March 2023
 
  schedule:
    - cron: "00 00 * * 1-5"
  workflow_dispatch:

jobs:
  check-in:
    env:
      ACCOUNT_EMAIL: ${{ secrets.ACCOUNT_EMAIL }}
      ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
      GEO_LATITUDE: ${{ secrets.GEO_LATITUDE }}
      GEO_LONGITUDE: ${{ secrets.GEO_LONGITUDE }}
      CHECK_TYPE: "CHECK_IN"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Checking In
        run: node index.js
